language: go
script:
  - go build
  - bash tests/test1.sh
deploy:
  provider: releases
  api_key:
    secure: q3U+IePO1t+GC5GyhDPVZA91eEKaX9hZRd0689dOO5i6qzGVxy8MVqaDJRiNGJ5V/CmOZQFRrJCqw7v6Aw3zk2kSS1Q1PkjzHYBkgXs6C4S57XVwGutad479d+AbjVPWOTMOojJPY6pV1XLbZQE//xvua87w7Q7YQgtZabG2h3CfdGsKUu4oQGcN+DlYV1YhjjB7fGs1C6mCtbSGnK0ZVDLnbXUEakIGoGHLwm+TQacVO9OinfCqiE69Ef7dtL6UCVYFAwCHzYu+i1DL8EdZ5Fq9cVe/lKQMdBXzVC/wSdVscxiIdW90gmEyK1BK9qYiiH3osYj1C4N3pq49iEeLNn9odp6x7Qj1II5PK/kBj6YGnWoromF6pkw2+j/cYyb43G2iWNoDrmEP6xw4s/CQ5hkoVbaU2QAMprMG7ULs1BYvgEIFr3nOY7MRLfuSrlnT7w0v3dFxqym85O2omwbazy9fBymK23FJqYofoR9Xpg+jhgu5p2XeADeTxSu8TwIdQLO2GJ3JSQ6tCmSblqPAFYUbIuUSAh6xpHxNP44Uv9GiATXnh5rBeI+PkKVKJCmlzxUBlIY+S54WU6zsPTO4EGGkmHlkBystNuLL6wi917C/rR5LtnOi4Ee1j6233laAecyFtKjjfybyilCzkNShXFIv1/u/JpDC8+jNDQlImAw=
  file: go-hello
  on:
    repo: anthshor/go-hello
